"""
Simple GFF3 parser for TransDecoder

Parses GFF3 files generated by LongOrfs phase.
"""

from typing import Generator, Dict, Any


def parse_gff3(gff3_file: str) -> Generator[Dict[str, Any], None, None]:
    """
    Parse a GFF3 file
    
    Args:
        gff3_file: Path to GFF3 file
        
    Yields:
        Dictionary for each GFF3 feature with keys:
        - seqid: sequence ID
        - source: source
        - type: feature type
        - start: start position (1-based)
        - end: end position (1-based)
        - score: score
        - strand: strand
        - phase: phase
        - attributes: dict of attributes
    """
    with open(gff3_file) as f:
        for line in f:
            line = line.strip()
            
            # Skip empty lines and comments
            if not line or line.startswith('#'):
                continue
            
            parts = line.split('\t')
            if len(parts) != 9:
                continue
            
            # Parse attributes
            attributes = {}
            for attr in parts[8].split(';'):
                if '=' in attr:
                    key, value = attr.split('=', 1)
                    attributes[key] = value.split(',')
            
            yield {
                'seqid': parts[0],
                'source': parts[1],
                'type': parts[2],
                'start': int(parts[3]),
                'end': int(parts[4]),
                'score': parts[5],
                'strand': parts[6],
                'phase': parts[7],
                'attributes': attributes
            }
